<?php

include 'ModelBase.php';

// Administrativo
include 'administrativo/Empresa.php';
include 'administrativo/EmpresaContato.php';
include 'administrativo/EmpresaEndereco.php';
include 'administrativo/EmpresaTelefone.php';

// Cadastros
include 'cadastros/Banco.php';
include 'cadastros/BancoAgencia.php';
include 'cadastros/Pessoa.php';
include 'cadastros/PessoaFisica.php';
include 'cadastros/PessoaJuridica.php';
include 'cadastros/PessoaContato.php';
include 'cadastros/PessoaTelefone.php';
include 'cadastros/PessoaEndereco.php';
include 'cadastros/Produto.php';
include 'cadastros/ProdutoGrupo.php';
include 'cadastros/ProdutoSubgrupo.php';
include 'cadastros/ProdutoUnidade.php';
include 'cadastros/ProdutoMarca.php';
include 'cadastros/NivelFormacao.php';
include 'cadastros/EstadoCivil.php';
include 'cadastros/BancoContaCaixa.php';
include 'cadastros/Cargo.php';
include 'cadastros/Cep.php';
include 'cadastros/Cfop.php';
include 'cadastros/Cliente.php';
include 'cadastros/Cnae.php';
include 'cadastros/Colaborador.php';
include 'cadastros/Contador.php';
include 'cadastros/Csosn.php';
include 'cadastros/CstCofins.php';
include 'cadastros/CstIcms.php';
include 'cadastros/CstIpi.php';
include 'cadastros/CstPis.php';
include 'cadastros/Fornecedor.php';
include 'cadastros/Municipio.php';
include 'cadastros/Ncm.php';
include 'cadastros/Papel.php';
include 'cadastros/Setor.php';
include 'cadastros/Transportadora.php';
include 'cadastros/Uf.php';
include 'cadastros/Usuario.php';
include 'cadastros/Vendedor.php';

// Tributação
include 'tributacao/TributGrupoTributario.php';
include 'tributacao/TributIcmsCustomCab.php';
include 'tributacao/TributIcmsCustomDet.php';
include 'tributacao/TributIss.php';
include 'tributacao/TributOperacaoFiscal.php';
include 'tributacao/TributConfiguraOfGt.php';
include 'tributacao/TributIpi.php';
include 'tributacao/TributPis.php';
include 'tributacao/TributCofins.php';
include 'tributacao/TributIcmsUf.php';

// NF-e
include 'nfe/NfeAcessoXml.php';
include 'nfe/NfeCabecalho.php';
include 'nfe/NfeCana.php';
include 'nfe/NfeCanaDeducoesSafra.php';
include 'nfe/NfeCanaFornecimentoDiario.php';
include 'nfe/NfeCteReferenciado.php';
include 'nfe/NfeCupomFiscalReferenciado.php';
include 'nfe/NfeDeclaracaoImportacao.php';
include 'nfe/NfeDestinatario.php';
include 'nfe/NfeDetEspecificoArmamento.php';
include 'nfe/NfeDetEspecificoCombustivel.php';
include 'nfe/NfeDetEspecificoMedicamento.php';
include 'nfe/NfeDetEspecificoVeiculo.php';
include 'nfe/NfeDetalhe.php';
include 'nfe/NfeDetalheImpostoCofins.php';
include 'nfe/NfeDetalheImpostoCofinsSt.php';
include 'nfe/NfeDetalheImpostoIcms.php';
include 'nfe/NfeDetalheImpostoIcmsUfdest.php';
include 'nfe/NfeDetalheImpostoIi.php';
include 'nfe/NfeDetalheImpostoIpi.php';
include 'nfe/NfeDetalheImpostoIssqn.php';
include 'nfe/NfeDetalheImpostoPis.php';
include 'nfe/NfeDetalheImpostoPisSt.php';
include 'nfe/NfeDuplicata.php';
include 'nfe/NfeEmitente.php';
include 'nfe/NfeExportacao.php';
include 'nfe/NfeFatura.php';
include 'nfe/NfeImportacaoDetalhe.php';
include 'nfe/NfeInformacaoPagamento.php';
include 'nfe/NfeItemRastreado.php';
include 'nfe/NfeLocalEntrega.php';
include 'nfe/NfeLocalRetirada.php';
include 'nfe/NfeNfReferenciada.php';
include 'nfe/NfeNumero.php';
include 'nfe/NfeNumeroInutilizado.php';
include 'nfe/NfeProcessoReferenciado.php';
include 'nfe/NfeProdRuralReferenciada.php';
include 'nfe/NfeReferenciada.php';
include 'nfe/NfeResponsavelTecnico.php';
include 'nfe/NfeTransporte.php';
include 'nfe/NfeTransporteReboque.php';
include 'nfe/NfeTransporteVolume.php';
include 'nfe/NfeTransporteVolumeLacre.php';

// Sped
include 'sped/ViewSpedC190.php';
include 'sped/ViewSpedNfeDestinatario.php';
include 'sped/ViewSpedNfeDetalhe.php';
include 'sped/ViewSpedNfeEmitente.php';
include 'sped/ViewSpedNfeItem.php';